split:
  test_size: 0.2
  random_state: 42

model: 
  type: LogisticRegression
  C: 1.0 
  max_iter: 100
  penalty: 'l1' 
  solver: 'liblinear' 

paths:
  raw_data: data/raw/telco_churn.csv
  cleaned_data: data/cleaned/telco_churn_cleaned.csv 
  train_data: data/train.csv
  test_data: data/test.csv
  model_path: models/telco_churn.pkl
  metrics_path: metrics.json
